### ISSUE TITLE
How to use a fitted model as a prior in a new context

### ISSUE THREAD

**Issue by tniggs84** [GPflow/docs#7]
I'm working in an instance where I want to fit a GPR to some training data and then use the posterior as a prior for some new data.  I've fit the GPR to the data and things look good on that end, but I am stuck trying to feed the model in as a prior.  The documentation does include this link on "[Updating Model with New Data](https://gpflow.readthedocs.io/en/master/notebooks/tailor/updating_models_with_new_data.html)" that looks like it could be helpful, but the stub is empty.  

I'm new to GPFlow and can't see in the documentation if such a thing is even possible.  If you can provide me with any assistance, I would be most grateful!

**Comment by st--** [comment]
@tniggs84 this repository only contains the autogenerated documentation and hence isn't monitored regularly; for issues with the code itself (bugs/feature requests) please raise them on the main repo at [github.com/GPflow/GPflow](https://github.com/GPflow/GPflow); questions like this one (how to do something _with_ GPflow) are more appropriate for stackoverflow (use the [gpflow tag](https://stackoverflow.com/tags/gpflow). Thanks :)
