### ISSUE TITLE
Should plot "sigmoid of mu" instead of mu

### ISSUE THREAD

**Issue by yezhengli-Mr9** [GPflow/docs#8]
After `mu, var = m.predict_f(x_grid)` in [classification.ipynb](https://github.com/GPflow/docs/blob/master/doc/source/notebooks/basics/classification.ipynb), it should be 
`plt.fill_between(x_grid.flatten(), np.ravel(sigmoid(mu + 2 * np.sqrt(var))), np.ravel(sigmoid(mu - 2 * np.sqrt(var))), alpha=0.3, color="C0")`.
with `def sigmoid(x): return 1/(1+np.exp(x))`
instead of 
`plt.fill_between(x_grid.flatten(), np.ravel(mu + 2 * np.sqrt(var)), np.ravel(mu - 2 * np.sqrt(var)), alpha=0.3, color="C0")`.

**Comment by yezhengli-Mr9** [comment]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/16505983/92548251-873eb680-f224-11ea-97be-6e219b2f0c70.png">

**Comment by st--** [comment]
Hi @yezhengli-Mr9 , it'd be great if you could open this issue on the main repo at [github.com/GPflow/GPflow](https://github.com/GPflow/GPflow); this repo only contains the auto-generated docs and isn't monitored regularly! thank you for raising :)

**Comment by st--** [comment]
Actually, in this case the notebook & plot are correct as is: we wanted to show both the posterior of the latent function itself (blue lines for samples and blue shade for 95% confidence interval), and samples of the posterior of the class probability (orange samples). Note that sigmoid(mu +/- 2 * np.sqrt(var)) are _not_ the confidence interval bounds on p (I don't think there's an easy way of doing it analytically; the correct way would be to compute very many samples and use np.quantile to empirically determine 5/95% confidence bands).
